language: python

sudo: true

matrix:
    include:
      - os: linux
        dist: trusty
        python: 3.6
      - os: osx
        osx_image: xcode10.2
        language: shell

install: pip3 install -r requirements.txt

script:
  - pytest --cov=methods/ --cov-report term

after_success:
  - codecov
